#!/bin/bash

set -x

nvidia-smi

# Run with the configured parameters
./SRBMiner-MULTI \
    --algorithm "$ALGO" \
    --pool "$POOL_ADDRESS" \
    --wallet "$WALLET_USER.$WORKER" \
    ${PASSWORD:+--password "$PASSWORD"} \
    $EXTRAS \
    --keepalive true \
    --pearl-k2

