#!/bin/bash

set -x

# Run with the configured parameters
exec ./SRBMiner-MULTI \
    --algorithm "$ALGO" \
    --pool "$POOL_ADDRESS" \
    --wallet "$WALLET_USER.$WORKER" \
    ${PASSWORD:+--password "$PASSWORD"} \
    $EXTRAS \
    --keepalive true

